### ISSUE TITLE
How do I deal with bots having socket problems?

### ISSUE THREAD

**Issue by StephanieSunshine** [obrie/turntabler#30]
It seems that as of last Friday that turntable did something that disconnects a socket after a set time and sometimes the bots aren't catching it.  Someone pointed out to me that when turntable went down last Friday that none of the bots showed back up until they were restarted.  Is there anyway to set a timer or something to make sure that a bot isn't spacing out?

I get timeout and reconnect, but they don't seem like they are enough anymore.

Thanks

**Comment by obrie** [comment]
@FuzzySunshine that's odd -- it certainly should automatically reconnect.  I'll have to look into that.

**Comment by jasonhazel** [comment]
I believe I'm getting the same issue. Debug is here: https://gist.github.com/mrhazel/5630352

I am now unable to keep my bot logged in for longer than a minute or two.

**Comment by obrie** [comment]
@mrhazel Heartbeats weren't being respected properly .. this was fixed in 0.3.4.

@FuzzySunshine I think I've noticed something similar -- I'll try to get a fix in the next week or so.  Basically there should be an expectation of receiving a heartbeat -- and if we don't get one, then the client should be realizing the connection has gone bad.

**Comment by StephanieSunshine** [comment]
So far the new releases have helped!  I'm not seeing it happen nearly as often ( I haven't seen one in a while )
